#!/bin/bash
#
# adb-backup-extract - Extract backups from your Android apps

declare -a REQUIRES=(adb tar)

if (($# < 1))
then
    echo "USAGE: $(basename "$0") APP_UUID [APP_UUID...]"
    exit 1
fi

for CMD in "${REQUIRES[@]}"
do
    command -v "$CMD" > /dev/null ||
    {
        echo "Missing required command: ${CMD}" >&2
        exit 2
    }
done

for UUID in "${@}"
do
    adb backup -f "/tmp/${UUID}-data.ab" -noapk "${UUID}"
    [[ -f "/tmp/${UUID}-data.ab" ]] &&
    {
        [[ -d "${UUID}" ]] ||
        mkdir "${UUID}" &&
        {
            cd "${UUID}"
            # Source: https://android.stackexchange.com/a/78183
            (
                printf "\x1f\x8b\x08\x00\x00\x00\x00\x00"
                tail -c +25 "/tmp/${UUID}-data.ab"
            ) | tar xfvz -
            cd ..
        }
    }
done
