#!/bin/bash
#
# curl-size - Quickly get the human-readable size for the given(s) URL(s)

set -o pipefail

declare -r KB=1024
declare -r MB=$((KB * 1024))
declare -r GB=$((MB * 1024))
declare    PREFIX
declare -a REQUIRES=(bc)
declare -i SIZE

for CMD in "${REQUIRES[@]}"
do
    command -v "$CMD" > /dev/null ||
    {
        echo "Missing required command: ${CMD}" >&2
        exit 1
    }
done

for URL in "$@"
do
    SIZE=$(curl -LIs "$URL" | grep -i -e ^'content-length' | tr -d '\r' | cut -f2 -d\ )
    if (($? == 0))
    then
        (($# > 1 )) && PREFIX="${URL}: "
        ((SIZE > GB)) && echo "${PREFIX}$(bc -l <<< "scale=2; $SIZE / $GB") GB" && continue
        ((SIZE > MB)) && echo "${PREFIX}$(bc -l <<< "scale=2; $SIZE / $MB") MB" && continue
        ((SIZE > KB)) && echo "${PREFIX}$(bc -l <<< "scale=2; $SIZE / $KB") KB" && continue
        echo "${URL}: ${SIZE} B"
    else
        echo "${URL}: Failed to get content-length" >&2
    fi
done
