#!/bin/bash
#
# duration - Print duration for the given media file(s)

declare    DURATION
declare -a REQUIRES=(mediainfo)

if (($# < 1))
then
    echo "USAGE: $(basename "$0") MEDIA_FILE [MEDIA_FILE...]"
    exit 1
fi

for CMD in "${REQUIRES[@]}"
do
    command -v "$CMD" > /dev/null ||
    {
        echo "Missing required command: ${CMD}" >&2
        exit 2
    }
done

for FILE in "${@}"
do
    [ -f "$FILE" ] &&
    DURATION=$( mediainfo "$FILE" | \
                grep -e "Duration" --max-count=1 | \
                cut -f 1 -d ":" --complement | \
                sed "s/^ //g" )
    [[ $DURATION ]] &&
    echo -e "\e[01;35m$( basename "$FILE" )\e[0m - $DURATION"
done
