#!/bin/env python3
#
# get-chrome-user-agent - Get Google Chrome's user agent

from selenium.webdriver import Chrome
from selenium.webdriver.chrome.options import Options

options = Options()
options.headless = True
driver = Chrome(options=options)
print(driver.execute_script('return navigator.userAgent;').replace('Headless', ''))
driver.quit()
