#!/bin/sh
#
# hide-applications - Set NoDisplay in desktop files

if [ $# -eq 0 ]
then
    echo "USAGE: $(basename "$0") DESKTOP_FILE [DESKTOP_FILE...]"
    exit 1
fi

mkdir -p "$HOME/.local/share/applications/"

for APP in "${@}"
do
    if [ -f "/usr/share/applications/$APP" ]
    then
        DESKTOP_FILE="/usr/share/applications/$APP"
    elif [ -f "/usr/share/applications/$APP.desktop" ]
    then
        DESKTOP_FILE="/usr/share/applications/$APP.desktop"
    else
        printf '%s\n' "[Desktop Entry]\nName=$APP" > "$HOME/.local/share/applications/$APP.desktop"
    fi
    OUTPUT_FILE=$(basename "$DESKTOP_FILE")
    [ -f "$HOME/.local/share/applications/$OUTPUT_FILE" ] || cp "$DESKTOP_FILE" "$HOME/.local/share/applications/$OUTPUT_FILE"
    printf '%s\n' 'NoDisplay=true' >> "$HOME/.local/share/applications/$OUTPUT_FILE" # TODO: appending isn't a proper solution
done
