#!/bin/bash
#
# pdfcount - Count the total lines in one or more PDF files

declare -i PAGES
declare -r REQUIRES=(file pdfinfo)
declare -i TOTAL

if (($# < 1))
then
    echo "USAGE: $(basename "$0") FILE [FILE...]"
    exit 1
fi

for CMD in "${REQUIRES[@]}"
do
    command -v "$CMD" > /dev/null ||
    {
        echo "Missing required command: ${CMD}" >&2
        exit 2
    }
done

for FILE in "${@}"
do
    [[ $(file --mime-type "$FILE" | cut -f2- -d/) == "pdf" ]] || continue
    PAGES=$( pdfinfo "$FILE" 2> /dev/null | grep "^Pages:" | sed "s/[^0-9]*//" )
    (( PAGES > 0 )) &&
    {
        echo -e "\e[01;35m$FILE\e[0m - $PAGES page`((PAGES > 1)) && echo s`"
        ((TOTAL += PAGES))
    }
done
(( TOTAL > PAGES )) &&
echo "$TOTAL total pages."
