#!/bin/bash
#
# run-in-default-terminal - Run a command using the default terminal

declare -a REQUIRES=(gsettings)
declare    TERM_EXEC
declare    TERM_EXEC_ARG

if (($# < 1))
then
    echo "USAGE: $(basename "$0") COMMAND [ARGUMENT] [ARGUMENT...]"
    exit 1
fi

for CMD in "${REQUIRES[@]}"
do
    command -v "$CMD" > /dev/null ||
    {
        echo "Missing required command: ${CMD}" >&2
        exit 2
    }
done

TERM_EXEC=$(gsettings get org.gnome.desktop.default-applications.terminal exec | tr -d \')
TERM_EXEC_ARG=$(gsettings get org.gnome.desktop.default-applications.terminal exec-arg | tr -d \')

if hash "$TERM_EXEC"
then
    command ${TERM_EXEC} ${TERM_EXEC_ARG} "${@}"
fi
