#!/bin/sh
#
# update-pot-references - Update references for a POT file

if (($# < 2))
then
    echo "USAGE: $(basename "$0") POT_FILE SRC_FILE [SRC_FILE...]"
    exit 1
fi

for FILE in "${@}"
do
    [[ -f "$FILE" ]] ||
    {
        echo "File not found: ${FILE}"
        exit 2
    }
done

INPUT_FILE="$1"
shift

for LINE in $(grep -n -e '^msgid ' "$INPUT_FILE" | cut -f1 -d:)
do
    [[ $(sed -n $((LINE - 1))p "$INPUT_FILE") =~ ^"#: " ]] || continue
    MSGID=$(sed -n ${LINE}p "$INPUT_FILE" | cut -f1 -d\  --complement)
    REFERENCES=$(grep -Hn "\$${MSGID}" ${@} | cut -f1,2 -d: | tr '\n' ' ')
    [[ -z $REFERENCES ]] &&
    {
        echo "WARNING: No reference found for line ${LINE}: $MSGID"
        continue
    }
    sed -i "$((LINE - 1))s~.*~#: ${REFERENCES}~" "$INPUT_FILE"
done
