#!/bin/sh
#
# update-pot-references - Update references for a POT file

if (($# < 2))
then
    echo "USAGE: $(basename "$0") POT_FILE SRC_FILE [SRC_FILE...]"
    exit 1
fi

for FILE in "${@}"
do
    [[ -f "$FILE" ]] ||
    {
        echo "File not found: ${FILE}"
        exit 2
    }
done

INPUT_FILE="$1"
shift
TMP_FILE="/tmp/${RANDOM}.pot"
cp "$INPUT_FILE" "$TMP_FILE"

for LINE in $(grep -n -e '^msgid ' "$TMP_FILE" | cut -f1 -d:)
do
    [[ $(sed -n $((LINE - 1))p "$TMP_FILE") =~ ^"#: " ]] || continue
    MSGID=$(sed -n ${LINE}p "$TMP_FILE" | cut -f1 -d\  --complement)
    REFERENCES=$(grep -Hn "\$${MSGID}" ${@} | cut -f1,2 -d: | tr '\n' ' ')
    [[ -z $REFERENCES ]] &&
    {
        echo "WARNING: No reference found for line ${LINE}: $MSGID"
        continue
    }
    sed -i "$((LINE - 1))s~.*~#: ${REFERENCES%% }~" "$TMP_FILE"
done

if ! cmp "$INPUT_FILE" "$TMP_FILE" > /dev/null 2>&1
then
    diff "$INPUT_FILE" "$TMP_FILE"
    echo -n "Update POT file? (y/N) "
    read UPDATE_FILE
    [[ ${UPDATE_FILE,,} =~ (y|yes) ]] &&
    {
        sed -i "s/\(\"POT-Creation-Date: \)\(.*\)/\1$(date '+%Y-%m-%d %H:%M%z')\\\n\"/" "$TMP_FILE"
        cp -f "$TMP_FILE" "$INPUT_FILE" &&
        echo "The file '$INPUT_FILE' was updated."
    }
else
    echo "Nothing to do."
fi

rm -f "$TMP_FILE"
